[package]
name = "common"
version = "0.1.0"
edition = "2024"
description = "Shared primitives and utilities for the Bizhi wallpaper system."

[dependencies]
anyhow.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
